### ISSUE TITLE
Create shell script

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/PecoRename#12]
On clicking Create shell script it says "What shall I do ? "
Which might confuse new users .  One line instruction could be added .

**Comment by janus2** [comment]
I think this "tools" is totally useless, I can not think to a use case...

**Comment by humdingerb** [comment]
I tend to agree. It creates a script that does the exact renaming of those exact files. That's hardly useful for anything. It would make sense if the script would implement the search/rename criteria  set in the GUI and would then be applied to all files of a folder or a list of supplied files.

**Comment by janus2** [comment]
I think we can remove tools and the menuItem "New" could be another candidate...

**Comment by janus2** [comment]
What do we do we remove tools and New?

**Comment by humdingerb** [comment]
+1

"New" would only make sense, if one could collect a set of files with additional drag&drops, for example. Then getting a clean slate with "New" would be useful. But since currently ever drag&drop etc. starts the list from scratch, it's not really needed.

**Comment by janus2** [comment]
Remove the useless tools in PR #37
