### ISSUE TITLE
Change Case

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/PecoRename#13]
Currently PecoRename only allows UPPERCASE/lowercase . 
Few more case like : 
Sentence case
Title Case
tOGGLE cASE could be added .

**Comment by bach5000** [comment]
Looks fun. I think I'll try this :)

**Comment by janus2** [comment]
I think toggle case make no sense. Sentence and Title can be useful. Keep in mind that you must use the utf8 encoding no ASCII.

**Comment by bach5000** [comment]
@janus2 Okay.

**Comment by waddlesplash** [comment]
BString's upper/lower case functions are UTF8 (I think... I didn't look at the implementation...)

**Comment by janus2** [comment]
From the BeBook
> Currently, BString only supports assignment and retrieval of strings that contain single-byte characters. If you want to use a BString to store a string that contains multi-byte (UTF8) characters, you have to flatten the string yourself and adjust the character count arguments accordingly.

I look into the implementation and  they use the c function than convert only ASCII
Even a Capitalize() and CapitalizeEachWord() exist, it is a shame they are not UTF8 compliant.

**Comment by janus2** [comment]
Just check Pe "Text>Change case" is ASCII

**Comment by scottmc** [comment]
https://stackoverflow.com/questions/9929147/how-do-i-convert-a-utf-8-string-to-upper-case

**Comment by janus2** [comment]
Yes ICU has upper lower and title case, but the important question is are the performances good, these methods must be lightning fast.

**Comment by bach5000** [comment]
Wait... what are we going for: UTF8 or ASCII?
I'm confused :0

**Comment by janus2** [comment]
UTF8

**Comment by bach5000** [comment]
Oh, okay.
So we somehow have to convert ASCII to UTF8 and figure out the rest.

**Comment by janus2** [comment]
ASCII is a subset of UTF8, you can complete the modifications suggested. We will find a method to transform the name in the future. I think ICU for this, can be slow because we need to convert each string in their format, maybe glib could be a little faster. Will see

**Comment by bach5000** [comment]
Ok.

**Comment by janus2** [comment]
Unless @scottmc has something different in mind it is his decision that counts.:-P

**Comment by bach5000** [comment]
@janus2 That's true...

**Comment by janus2** [comment]
We must consider that almost all Haiku doesn't keep into account this problem at all... the main functions that the applications use just manipulate the string as ASCII, so this does a good job to manage these transformations instead to avoid the problem completely.

**Comment by waddlesplash** [comment]
> From the BeBook
> We must consider that almost all Haiku doesn't keep into account this problem at all

That's not true, though (it is for the toUpper/toLower stuff) at least not overall: BString has some UTF-8 awareness in Haiku, see https://www.haiku-os.org/docs/api/classBString.html#details

> BString does have some understanding of UTF-8 and it can be used for the manipulation of UTF-8 strings

All of the `*Chars()` functions, e.g. `CountChars()`, `CopyCharsInto()`, `CharAt()` are UTF-8 aware.

**Comment by janus2** [comment]
This is cheating those are function where you must check a bit, those where you need to know the UTF8 tables are nowhere.

**Comment by janus2** [comment]
As suggested by @pulkomandy for another issue could be interesting investigate the BUnicodeChar class.
