### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/PecoRename#14]
When entering a random "Find pattern" which isn't there in the file name no error/warning is generated . 
A warning or error message could be displayed saying something like "PecoRename couldn't find entered pattern"

**Comment by humdingerb** [comment]
The live preview column shows the future filenames. If a row is empty, the pattern wasn't found for that file. A special warning if the pattern doesn't apply to *any* file in your list doesn't seem necessary.

**Comment by janus2** [comment]
I agree with @humdingerb can we close this?

**Comment by humdingerb** [comment]
Sure we can. :)
Hasn't waddlesplash invited you to HaikuArchives yet? The speed you churn out those PR, it creates too much work for the rest of us... :)

**Comment by janus2** [comment]
More are coming... ;-)
I feel rude to close an issue without asking.
I use PR so somebody can code review my changes.

**Comment by humdingerb** [comment]
Hope the "somebody" does... :)
Makes sense, creating a PR, but do merge yourself if there's no feedback for some time. And above all, don't wait on me. You're a much better coder... :)
