### ISSUE TITLE
Drawing artifacts at the FileListView bottom

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/PecoRename#15]
![image](https://user-images.githubusercontent.com/1316513/34255288-0c335f08-e661-11e7-9c19-592139642c37.png)

**Comment by scottmc** [comment]
Just a comment here, many of these old BeOS caps still have the "Let's do it!" or similar buttons.  We should be updating these to be what users expect from a more modern system.  Also it just makes it easier when time comes to translate the strings.

Also the :-) may also be out of place these days.
