### ISSUE TITLE
Update locale files

### ISSUE THREAD

**Issue by janus2** [HaikuArchives/PecoRename#38]
I don't know if there is an automated way to align the other languages to the newly created English catalog. I mean add the new string and mark the modified one.

**Comment by humdingerb** [comment]
It's a bit time consuming, and get's worse when the number of languages increase...
How I do it:
* `make catkeys` to create the new en.catkeys (and sort those with som script)
* duplicate the en.catkeys for all languages (de.catkeys, it.catkeys...)
* open each of those catkeys in CatKeysEditor and import the existing old catkeys of each language.

Now people can open their language's catkeys in CatKeysEditor and filter to only show the untranslated strings.

Would be nice it the CatKeysEditor could automate this a bit and did some of this managing of a projects catkeys.

**Comment by janus2** [comment]
Without the sorting CatKeysEditor is unable to match the strings?

**Comment by humdingerb** [comment]
No. That sorting is just for convenience when translating. It keeps stuff that's related together.
