### ISSUE TITLE
Report window doesn't show horizontal scrollbar at start

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/PecoRename#42]
![report_no_hor_scroll](https://user-images.githubusercontent.com/6107158/34961187-9009416c-fa3e-11e7-92b2-7ab301617bc9.png)

Only after resizing the window, the horizontal sscroll bar appears. I think that was only after my small changes around 9b562095334833d63a8d9b47d3fe050bedde695d .
For the life of me, I cannot fix it. Calling Mr. @janus2 !

**Comment by janus2** [comment]
I cannot reproduce this bug. Can you try my PR #44?

**Comment by humdingerb** [comment]
Tried it, doesn't work.

My last commit saving window positions, has "fixed" it somewhat. It's not missing anymore, once you have changed the window size once. From then on the scroll bar is always there.
I only noticed that after the commit when I removed the settings file.

Good enough "fix" or should I reopen.?

**Comment by janus2** [comment]
I don't know why but on my side the scrollbar is always present. I even try deleting the settings. It's strange because from your screenshot the statusbar is calculate but hidden.

**Comment by humdingerb** [comment]
You are on the latest commit, I assume...
What do you mean with "status bar"? You are looking at the "Report" window, right? :)

**Comment by humdingerb** [comment]
BTW, do you know if it's possible to save/restore column width for BColumnListView?

**Comment by janus2** [comment]
Yes, there is a SaveState and LoadState. Never tried it, I don't know if it works as expected.
Should save columns size, visibility, sort order.

**Comment by humdingerb** [comment]
I'll have a look, thanks!
