### ISSUE TITLE
Remove renamer should work in all direction combinations

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/PecoRename#43]
Hope I explain it clearly...
Only the following "Example 4" works as expected in all directions. The rest has issues.
(I cannot bend my little brain around the code, but at least I can try to describe what is and what should be...)

**Example 1: both from left**
> "Remove characters from position" "0" "from the front (left)"
> "to position" "3" "from the front (left)"

Works: It removes the first 3 chars, the filename "template" becomes "plate"
_If you switch the 0 and 3, it should be the same, but that doesn't work (preview empty)._

**Example 2: both from right**
> "Remove characters from position" "3" "from the back (right)"
> "to position" "0" "from the back (right)"

Works: It removes the last 3 chars, the filename "template" becomes "templ"
_If you switch the 0 and 3, it should be the same, but that doesn't work (preview empty)._

**Example 3: right to left**
> "Remove characters from position" "3" "from the back (right)"
> "to position" "0" "from the front (left)"

_Doesn't work.  The filename "template" should become "ate" (preview empty).
If you switch the 0 and 3, "template" should become "tem", but doesn't (preview empty)._

**Example 4: left to right**
> "Remove characters from position" "3" "from the front (left)"
> "to position" "0" "from the back (right)"

Works:  It removes the last 4 chars, the filename "template" becomes "temp".
If you switch the 0 and 3 it works, too: "template" becomes "ate", look:

![renamer_remove](https://user-images.githubusercontent.com/6107158/34963103-03a752b4-fa47-11e7-9859-c560745f9bc8.png)

**Comment by janus2** [comment]
If I am not wrong the example 4 the results should be "tem" and "ate".
