### ISSUE TITLE
PecoRename became CPU hungry

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/PecoRename#5]
After latest patch PecoRename is using a lot of cpu by just having its window open.
It also reproduces a bug in app_server when moving some other window above it.

**Comment by pulkomandy** [comment]
I can't reproduce either problem. I have built PecoRename, and run it with ./PecoRename from the build directory. Is there something more I need to do to trigger the issue?

**Comment by hannahyp** [comment]
Neither could I, but I was using VirtualBox.

**Comment by diversys** [comment]
Weird, I can'r replicate it at work in vbox. Will try again at home

**Comment by diversys** [comment]
Can't reproduce at home either. Welp.

**Comment by diversys** [comment]
Finally managed to reproduce. Launch PecoRename and change Panel background in Appearance preflet

**Comment by humdingerb** [comment]
Similar issue discovered by vanishakesswani  in #8 
- Change font size to 24 in Appearance .
- Open PecoRename
- Click default in Appearance
and your PecoRename won't respond .
