### ISSUE TITLE
Rename "Insert / replace" to "Insert / overwrite" ?

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/PecoRename#52]
I think "overwrite" is more descriptive that "replace". It also distincts this renamer better from "Search / replace".

@janus2 et al:
Can I get a +1? A thumbs-up? An "Amen!"?

**Comment by janus2** [comment]
👍 👍 👍

**Comment by janus2** [comment]
![abed](https://user-images.githubusercontent.com/10423645/35183875-2e76ea14-fded-11e7-9435-e8683236b26d.gif)

**Comment by humdingerb** [comment]
Thank you, thank you thank you! :)

@janus2 
What do you say, should I change the names of the variables as well? I think so.
What about the flattend BMessage fields for the preferences? This would mean that the last saved settings isn't found anymore, but I'd consider that a very minor loss...

**Comment by janus2** [comment]
> What about the flattend BMessage fields for the preferences? This would mean that the last saved settings isn't found anymore, but I'd consider that a very minor loss...

Do you mean for retro compatibility?

**Comment by humdingerb** [comment]
Yes. But seeing as everytime you use PecoRename it rewrites those past settings, and you practically change the settings every time, I doubt many will even notice that their past setting is not there this one time.

**Comment by janus2** [comment]
yes
