### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/PecoRename#7]
![broken_ui](https://cloud.githubusercontent.com/assets/24365311/21348796/c2f907b8-c6d4-11e6-982d-5518671a2cc6.png)

On increasing size UI doesn't work as it is expected to .  Screenshot as reference . 
Replicating is easy still if you're unable to reply back I will write down the complete instructions .

**Comment by humdingerb** [comment]
It's OK. An obvious and long-annoying bug...
